# Q1

In [4]:
import numpy as np
A = np.array([
    [44, 38, 21],
    [32, 28, 15],
    [24, 20, 10]
])
B = np.array([1412, 1024, 728])
# AX=B
solution = np.linalg.solve(A, B)
num_males, num_females, num_kids = solution
print(f"Number of males: {int(num_males)}")
print(f"Number of females: {int(num_females)}")
print(f"Number of kids: {int(num_kids)}")

Number of males: 12
Number of females: 9
Number of kids: 24


# Q2

In [ ]:
import numpy as np
x1, y1, z1 = map(int, input("Enter x1, y1, z1 separated by commas: ").split(','))
x2, y2, z2 = map(int, input("Enter x2, y2, z2 separated by commas: ").split(','))
arr3d1 = np.random.randint(1, 101, size=(x1, y1, z1))
arr3d2 = np.random.randint(1, 101, size=(x2, y2, z2))

divBy51=arr3d1[arr3d1%5==0]
divBy42=arr3d2[arr3d2%4==0]
print(f"Divisible by 5 in arr3d1: {divBy51}")
print(f"Divisible by 4 in arr3d2: {divBy42}")

combined_1d = np.concatenate((arr3d1.flatten(), arr3d2.flatten()))
side_length = int(np.floor(np.sqrt(combined_1d.size)))
largest_square_matrix = combined_1d[:side_length**2].reshape(side_length, side_length)
print(f"Largest possible square matrix:\n{largest_square_matrix}")


Divisible by 5 in arr3d1: []
Divisible by 4 in arr3d2: [64]
Largest possible square matrix:
[[22]]


# Q3

In [29]:
import numpy as np
def Create_Array(*args):
    res=np.zeros((len(args),len(args)))
    for i,elm in enumerate(args):
        res[i,i]=elm
    return res


new_arr=Create_Array(1,2,3,4,5)
print(new_arr)
    

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]
